### ISSUE TITLE
Errors using Set-CsOnlineVoicemailUserSettings

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/office-docs-powershell#10478]
As of the last 2 days, we have been receiving the following error while provisioning Enterprise Voice. This was first noticed in our runbooks last night.

Any suggestions or ideas would be greatly appreciated

`Set-CsOnlineVoicemailUserSettings -Identity $Acct.SipAddress -PromptLanguage 'en-AU' -ErrorAction Stop
Set-CsOnlineVMUserSetting_SetExpanded: C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.3\custom\Merged_custom_PsExt.ps1:8574
Line |
8574 |              $result = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set- …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A valid identity is required to request tokens on behalf of them Parameter name: identity`

**Comment by Thurmus** [comment]
I have just come across the exact same thing, 

Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsOnlineVMUserSetting : A valid identity is required to request tokens
on behalf of them
Parameter name: identity
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.5.0\custom\PsExt\Merged_custom_PsExt.ps1:6114 char:9
+         $result = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsOn ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = si...emailSettings }:<>f__AnonymousType73`2) [Set-CsOnli
   neVMUserSetting_SetExpanded], RestException
    + FullyQualifiedErrorId : 400,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsOnlineVMUserSetting_SetExpa
   nded

**Comment by dappleby300** [comment]
This is occuring for me as well. Same error for both Get-CsOnlineVoicemailUserSettings and Set-CsOnlineVoicemailUserSettings. We have two tenants and its failing in both

**Comment by JeroenHems** [comment]
For me too, I was running an outdated version of the Powershell module, updating to the latest version (4.9.3) had no effect.

**Comment by JensTrier** [comment]
Thanks for the feedback. The team is investigating the issue.

**Comment by RichWorld-Tech** [comment]
This is happening on our tenant as well. Same error for both Get-CsOnlineVoicemailUserSettings and Set-CsOnlineVoicemailUserSettings.

**Comment by jtaylor555** [comment]
I am having this issue as well. Do we have a resolution planned?

**Comment by JensTrier** [comment]
AFAIK the issue originally reported here should have been resolved some time ago and the set/get cmdlets also works in my tenant. My recommendation is that you open a Microsoft support case and they will work with you to investigate.

**Comment by yogkumgit** [comment]
@JensTrier Thank you very much for sharing this explanation. @kpinel Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ckarawani** [comment]
not sure if others are seeing this, but looks like the issue is back. Would be good to understand if there's a documented root cause for when this happens?
