### ISSUE TITLE
Please add this as an exxample on how to reference a Call Queue as a menu option in an AA

### ISSUE THREAD

**Issue by JensTrier** [MicrosoftDocs/office-docs-powershell#3521]
$aaName = "Main Auto Attendant"
$language = "en-US"
$greetingText = "Welcome to Contoso"
$mainMenuText = "To reach your party by name, say it now. To talk to Sales, please press 1. To talk to User2 press 2. Please press 0 for operator"
$afterHoursText = "Sorry Contoso is closed. Please call back during week days from 7AM to 8PM. Goodbye!"
$tz = "Romance Standard Time"
$operatorId=(Get-CsOnlineUser -Identity "sip:user1@contoso.com").ObjectId
$user1Id=(Get-CsOnlineUser -Identity "sip:user2@contoso.com").ObjectId
$salesCQappinstance = (Get-CsOnlineUser -Identity "sales@contoso.com").ObjectId  # one of the application instances associated to the Call Queue
$tr1 = New-CsOnlineTimeRange -Start 07:00 -End 20:00

# After hours
$afterHoursSchedule = New-CsOnlineSchedule -Name "After Hours" -WeeklyRecurrentSchedule -MondayHours @($tr1) -TuesdayHours @($tr1) -WednesdayHours @($tr1) -ThursdayHours @($tr1) -FridayHours @($tr1) -Complement
$afterHoursGreetingPrompt = New-CsAutoAttendantPrompt -TextToSpeechPrompt $afterHoursText
$afterHoursMenuOption = New-CsAutoAttendantMenuOption -Action DisconnectCall -DtmfResponse Automatic
$afterHoursMenu = New-CsAutoAttendantMenu -Name "AA menu1"  -MenuOptions @($afterHoursMenuOption)
$afterHoursCallFlow = New-CsAutoAttendantCallFlow -Name "After Hours" -Menu $afterHoursMenu -Greetings @($afterHoursGreetingPrompt)
$afterHoursCallHandlingAssociation = New-CsAutoAttendantCallHandlingAssociation -Type AfterHours -ScheduleId $afterHoursSchedule.Id -CallFlowId $afterHoursCallFlow.Id

# Business hours menu options
$operator = New-CsAutoAttendantCallableEntity -Identity $operatorId -Type User
$sales = New-CsAutoAttendantCallableEntity -Identity $salesCQappinstance -Type applicationendpoint
$user1 = New-CsAutoAttendantCallableEntity -Identity $user1Id -Type User
$menuOption0 = New-CsAutoAttendantMenuOption -Action TransferCallToOperator -DtmfResponse Tone0 -CallTarget $operator
$menuOption1 = New-CsAutoAttendantMenuOption -Action TransferCallToTarget -DtmfResponse Tone1 -CallTarget $sales
$menuOption2 = New-CsAutoAttendantMenuOption -Action TransferCallToTarget -DtmfResponse Tone2 -CallTarget $user1

# Business hours menu
$greetingPrompt = New-CsAutoAttendantPrompt -TextToSpeechPrompt $greetingText
$menuPrompt = New-CsAutoAttendantPrompt -TextToSpeechPrompt $mainMenuText
$menu=New-CsAutoAttendantMenu -Name "AA menu2" -Prompts @($menuPrompt) -EnableDialByName -MenuOptions @($menuOption0,$menuOption1,$menuOption2)
$callFlow = New-CsAutoAttendantCallFlow -Name "Default" -Menu $menu -Greetings $greetingPrompt

# AA
New-CsAutoAttendant -Name $aaName  -Language $language -CallFlows @($afterHoursCallFlow) -TimeZoneId $tz -Operator $operator -DefaultCallFlow $callFlow -CallHandlingAssociations @($afterHoursCallHandlingAssociation) -EnableVoiceResponse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57a54bfc-d94b-dfa3-bf51-73c19601fc8c
* Version Independent ID: 9c3b6b02-ace5-9345-7fb6-24c09ed685e9
* Content: [New-CsAutoAttendant (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendant?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @JensTrier, thank you for your feedback.

Looks like a good example. I will create a pull request to add it to the article. Could you help me to review it?

**Comment by JensTrier** [comment]
Sure, thanks!

Best regards
                             Jens

**Comment by dariomws306** [comment]
@JensTrier, could you help me to improve example description?

This is what I have now:

This example creates a new AA named _Main auto attendant_ that has the following properties:

- It sets a default call flow.
- It sets an after-hours call flow.
- It sets a business hours options.
- It references a call queue as a menu option.
- The default language is en-US.
- The time zone is set to Romance Standard.

Thanks!

**Comment by dariomws306** [comment]
You can see the "preview" here:
https://github.com/dariomws306/office-docs-powershell/blob/patch-20/skype/skype-ps/skype/New-CsAutoAttendant.md

**Comment by JensTrier** [comment]
Looks good, but please add:

  *   Sets user1 as operator
  *   Has user2 also as a menu option
  *   The AA is voice enabled

The last line of the PS script is missing

Best regards
                             Jens

**Comment by dariomws306** [comment]
Done! Thanks for your help!

This example creates a new AA named Main auto attendant that has the following properties:

It sets a default call flow.
It sets an after-hours call flow.
It sets a business hours options.
It references a call queue as a menu option.
The default language is en-US.
The time zone is set to Romance Standard.
It sets user1 as operator.
It has user2 also as a menu option.
The Auto Attendant is voice enabled.

**Comment by yogkumgit** [comment]
@kenwith please merge PR #3574

**Comment by JensTrier** [comment]
Hi,

You forgot to react on my latest feedback. The example 4 PS script is missing the last line (the most important part).

# AA
New-CsAutoAttendant -Name $aaName  -Language $language -CallFlows @($afterHoursCallFlow) -TimeZoneId $tz -Operator $operator -DefaultCallFlow $callFlow -CallHandlingAssociations @($afterHoursCallHandlingAssociation) -EnableVoiceResponse

Best regards
                             Jens

**Comment by dariomws306** [comment]
It's true! Sorry about that and thank you for noticing! 

I have added the last line.

Thank you again!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @JensTrier Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
