### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by 1AdamG** [MicrosoftDocs/office-docs-powershell#4749]
This link is not working in the begining of the page 
https://go.microsoft.com/fwlink/p/?linkId=182625

Also the tool can not be installed unless having"Microsoft Unified Communications Managed API 2.0 Core Runtime" which is not available for download on Microsoft website. Newer versions for UCM API Core Runtime do not work with Test-UMConnectivity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a9e60a8-3fc2-0a61-9d35-933f8e6d373a
* Version Independent ID: 34fbc2c4-8d99-c599-dc1a-e8e9df1a6fa7
* Content: [Test-UMConnectivity (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/unified-messaging/test-exchangeumcallflow?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/unified-messaging/Test-ExchangeUMCallFlow.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/unified-messaging/Test-ExchangeUMCallFlow.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@1AdamG, confirmed. I updated the link; it should b. The prerequisites for the tool (including the UCM API v2.0) are included on the download page.

Thanks for the feedback.

**Comment by 1AdamG** [comment]
If you click the updated link and try to see the perquisites, the link for Unified Communications Managed API 2.0, Core Runtime (64-bit) is not working.

And the tool it self doesn't work with newer versions than 2.0. that means this tool is no longer working. 

Either remove the tool or update it so it can work with newer versions of UCM API.
Regards

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please reply. Thanks

**Comment by chrisda** [comment]
Well, it looks like we need to remove the topic, then. I can't find anywhere to download UCMA 2.0.

Thanks for the feedback.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by 1AdamG** [comment]
Hi,
It's still the same issue.
Unified Communications Managed API 2.0, Core Runtime (64-bit)
<http://go.microsoft.com/fwlink/?LinkID=163815>
That is listed in the requirements for this tool doesn't exist and the link
to it doesn't work.

Regards,
Adam

Den lör 23 maj 2020 15:01Dario Woitasen <notifications@github.com> skrev:

**Comment by dariomws** [comment]
Hi @1AdamG, sorry my mistake, we fixed the Exchange module link at the top of the page but it´s not related to this issue.

Related to this issue, I cannot find the link https://go.microsoft.com/fwlink/p/?linkId=182625 in the article.

Thanks!

**Comment by 1AdamG** [comment]
Hi,

See attached picture.
[image: image.png]
Regards, Adam

Den mån 25 maj 2020 kl 16:36 skrev Dario Woitasen <notifications@github.com

**Comment by dariomws** [comment]
I cannot see the image. But I think I understand now, you are talking about this link:
![image](https://user-images.githubusercontent.com/33589238/82823701-712c0680-9e7e-11ea-8b26-045f6683e808.png)

I cannot update content on https://www.microsoft.com/en-us/download/ but I think that content will be removed soon as mentioned by @chrisda.

**Comment by 1AdamG** [comment]
Yes, that's right!

Okay, but back to the original reason the link was removed.

1. The tool requires UC Managed API 2.0
2. UC Managed API 2.0 doesn't exist anymore
3. That means the tool is obsolete

Either update the tool so it can support newer versions of UC Managed API
or remove the tool completely.

Why keep a tool that no one can use?

Regards,
Adam

Den mån 25 maj 2020 16:56Dario Woitasen <notifications@github.com> skrev:

**Comment by dariomws** [comment]
The link will be removed because on October 13, 2020, Exchange Server 2010 will reach end of support.

**Comment by chrisda** [comment]
The original issue was that the download link for the UCM API 2.0 wasn't available in the Test-ExchangeUMCallFlow topic. That topic is now gone, so there's nothing left to do on our end. We have no control or insight into what's available or not available in the Download Center. The suggestion would be to open a support ticket.

Thanks for the feedback.

Closing
